name: publish

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: bin
          path: bin
      - name: Publish
        run: |
          cd bin
          # publish the artifact


